PRAMAANA_SEED = [
    # ── High credibility ────────────────────────────────────────────────────
    {
        "article_title": "Operation Sindoor and the Evolution of India's Military Strategy Against Pakistan",
        "source_url": "https://warontherocks.com/2025/05/operation-sindoor-and-the-evolution-of-indias-strategy-against-pakistan/",
        "outlet": "War on the Rocks",
        "region": "india",
        "overall_score": 74,
        "verdict": "War on the Rocks is a peer-reviewed defence policy outlet with strong editorial standards. This piece by Arzan Tarapore traces India's strategic evolution across Uri, Balakot, and Operation Sindoor with credible sourcing and analytical restraint. The framing is Western-security-establishment adjacent, which slightly underweights Pakistani and civilian perspectives, but the core analysis is rigorously argued.",
        "dimensions": [
            {"name": "Source trust", "score": 81, "note": "Peer-reviewed defence journal, named expert author"},
            {"name": "Claim verifiability", "score": 78, "note": "Historical events cited are verifiable and documented"},
            {"name": "Cross-source consensus", "score": 72, "note": "Core thesis consistent with Indian strategic literature"},
            {"name": "Narrative transparency", "score": 70, "note": "Analytical framing, US-aligned security perspective"},
            {"name": "Contextual completeness", "score": 66, "note": "Pakistani civilian impact underexplored"},
        ],
        "source_funding": "War on the Rocks is an independent US-based defence and national security journal funded through subscriptions, institutional partnerships, and reader donations. It has no government or defence contractor funding and maintains an editorial firewall. Authors publish in their individual capacities.",
        "claims": [
            {"type": "fact", "text": "India launched Operation Sindoor on May 7, 2025, striking nine sites in Pakistan and Pakistan-administered Kashmir"},
            {"type": "fact", "text": "The operation was India's response to the Pahalgam terror attack of April 22, 2025, which killed 26 civilians"},
            {"type": "opinion", "text": "Operation Sindoor represents a decisive shift from deterrence-by-punishment to degradation-of-capacity"},
            {"type": "contested", "text": "The strike framework established a new escalation threshold that Pakistan is unlikely to challenge militarily"},
        ],
        "cross_source": [
            {"outlet": "Stimson Center", "stance": "agree", "note": "Independent US think tank corroborates the strategic evolution thesis"},
            {"outlet": "Dawn (Pakistan)", "stance": "diverge", "note": "Frames strikes as unprovoked aggression on civilian infrastructure"},
            {"outlet": "The Hindu", "stance": "partial", "note": "Confirms facts, more cautious on long-term strategic implications"},
            {"outlet": "Al Jazeera", "stance": "partial", "note": "Reports operation accurately but emphasises civilian casualty claims"},
        ],
        "narrative_beneficiary": "The Indian security establishment and proponents of a more assertive Indian posture benefit from this analytical frame. The piece implicitly validates the political decision to escalate beyond the Balakot precedent.",
        "missing_context": [
            "Civilian casualty figures from Pakistani sources — disputed but not engaged with in the analysis",
            "Pakistan's domestic political constraints that shaped its military response calculus",
            "The role of US and Chinese backchannel communications in bringing about the ceasefire",
        ],
    },

    # ── Mixed credibility ────────────────────────────────────────────────────
    {
        "article_title": "Biden says Israel has agreed to 'enduring' Gaza ceasefire proposal",
        "source_url": "https://www.aljazeera.com/news/2024/5/31/biden-says-israel-has-agreed-to-enduring-gaza-ceasefire-proposal",
        "outlet": "Al Jazeera",
        "region": "global",
        "overall_score": 61,
        "verdict": "Al Jazeera's coverage of Biden's ceasefire proposal is factually grounded and fills a genuine reporting gap. The piece accurately reports the three-phase proposal and Hamas's response. However, Israeli government counter-framing receives less depth than Palestinian reaction, and the headline's framing of Israel having 'agreed' was contested within hours — a nuance the article addresses only partially.",
        "dimensions": [
            {"name": "Source trust", "score": 67, "note": "Qatar state-funded, active Gaza correspondent network"},
            {"name": "Claim verifiability", "score": 69, "note": "Biden's speech is primary source, accurately reported"},
            {"name": "Cross-source consensus", "score": 63, "note": "Proposal details confirmed by Reuters and AP"},
            {"name": "Narrative transparency", "score": 58, "note": "Palestinian framing slightly dominant over Israeli position"},
            {"name": "Contextual completeness", "score": 53, "note": "Hamas's internal divisions on accepting deal not covered"},
        ],
        "source_funding": "Al Jazeera is funded by the Qatari government and the Al Thani royal family. Qatar hosts Hamas's political leadership and serves as a key ceasefire mediator, creating a structural editorial tension on Gaza coverage. Al Jazeera operates with day-to-day editorial independence but broad framing reflects Qatari foreign policy interests.",
        "claims": [
            {"type": "fact", "text": "President Biden announced a three-phase ceasefire proposal on May 31, 2024"},
            {"type": "fact", "text": "Phase one included a six-week ceasefire and Israeli withdrawal from populated Gaza areas"},
            {"type": "contested", "text": "Israel had agreed to the proposal — Israeli officials later walked back the characterisation"},
            {"type": "opinion", "text": "The proposal represented a significant shift in US posture toward pressuring Israel"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "partial", "note": "Confirms proposal, notes Israeli ambiguity on agreement immediately"},
            {"outlet": "Times of Israel", "stance": "diverge", "note": "Emphasises Netanyahu's insistence war goals not yet achieved"},
            {"outlet": "UN OCHA", "stance": "agree", "note": "Welcomed proposal, corroborates humanitarian corridor framework"},
            {"outlet": "BBC", "stance": "partial", "note": "Similar framing but gives more weight to Israeli government statements"},
        ],
        "narrative_beneficiary": "Qatar's diplomatic positioning as a credible ceasefire mediator is served by Al Jazeera's prominent international role. Palestinian political leadership benefits from coverage that frames Israel as the obstacle to peace. Biden administration benefits from the 'US as honest broker' angle.",
        "missing_context": [
            "Hamas's internal political split between Yahya Sinwar's military wing and the Doha-based political bureau on accepting any deal",
            "The proposal had been circulating for weeks — the 'announcement' was a political move ahead of US domestic political pressure",
            "Previous ceasefire proposals had collapsed at similar stages — historical context largely absent",
        ],
    },
    {
        "article_title": "Another India-US Defence Agreement, Same Old Obstacles",
        "source_url": "https://thewire.in/article/security/another-india-us-defence-agreement-same-old-obstacles",
        "outlet": "The Wire",
        "region": "india",
        "overall_score": 57,
        "verdict": "Rahul Bedi's analysis documents a genuine pattern of underdelivery in India-US defence co-development, with verifiable references to failed programmes like DTTI and iCET. The core thesis is supported by evidence. However, the piece curates expert opinion toward scepticism and omits significant counterevidence — actual technology transfers and joint production that have occurred — creating an imbalanced picture that serves a pre-formed conclusion.",
        "dimensions": [
            {"name": "Source trust", "score": 65, "note": "Independent, faced government pressure — editorial independence intact"},
            {"name": "Claim verifiability", "score": 63, "note": "DTTI and iCET failures documented and verifiable"},
            {"name": "Cross-source consensus", "score": 54, "note": "Minority view in Indian strategic community"},
            {"name": "Narrative transparency", "score": 52, "note": "Sceptical framing not disclosed as editorial position"},
            {"name": "Contextual completeness", "score": 47, "note": "GE-414 engine deal, MQ-9B purchase omitted as counterevidence"},
        ],
        "source_funding": "The Wire is funded through reader donations, institutional grants, and limited advertising. Has faced Enforcement Directorate raids targeting its founders, widely interpreted as government pressure. Donor base partially disclosed. Editorially independent with a discernible left-liberal editorial stance on security and foreign policy.",
        "claims": [
            {"type": "fact", "text": "The Defence Technology and Trade Initiative (DTTI) launched in 2012 produced no major co-development outcomes"},
            {"type": "fact", "text": "India and the US signed the Initiative on Critical and Emerging Technologies (iCET) in 2022"},
            {"type": "opinion", "text": "The latest defence framework risks repeating the cycle of lofty intent and limited delivery"},
            {"type": "contested", "text": "US export controls (ITAR) systematically prevent meaningful technology transfer to India"},
        ],
        "cross_source": [
            {"outlet": "Indian Express", "stance": "diverge", "note": "Points to GE-414 engine deal and MQ-9B as concrete deliverables"},
            {"outlet": "The Diplomat", "stance": "partial", "note": "Acknowledges obstacles but frames recent progress as more substantive"},
            {"outlet": "Foreign Policy", "stance": "partial", "note": "Notes structural ITAR problems but more optimistic on iCET trajectory"},
            {"outlet": "Times of India", "stance": "diverge", "note": "Frames India-US defence ties as genuinely transformative under Modi"},
        ],
        "narrative_beneficiary": "Opposition voices and non-alignment advocates in India benefit from a narrative that undermines confidence in US partnership. Indirectly, Russia and China benefit from coverage that portrays US-India defence deepening as unproductive and conditional.",
        "missing_context": [
            "India signed the $3.99 billion GE-414 engine co-production deal in 2023 — the largest technology transfer in India-US defence history",
            "India's purchase of 31 MQ-9B Predator drones ($3.7B) represents a significant procurement shift not mentioned",
            "ITAR reform has been ongoing and India received STA-1 designation in 2016, facilitating more transfers than the article implies",
        ],
    },
    {
        "article_title": "Dealing with the Taliban",
        "source_url": "https://www.dawn.com/news/1884874",
        "outlet": "Dawn",
        "region": "india",
        "overall_score": 54,
        "verdict": "Maleeha Lodhi, a former Pakistani ambassador, provides a sophisticated insider account of Pakistan's Taliban dilemma that is analytically stronger than typical government-aligned commentary. She acknowledges the TTP threat honestly. However, the piece consistently frames Pakistan as reacting to circumstances rather than examining Islamabad's historical role in creating them, and avoids the structural question of ISI's relationship with the Afghan Taliban.",
        "dimensions": [
            {"name": "Source trust", "score": 62, "note": "Credible author, Dawn under periodic establishment pressure"},
            {"name": "Claim verifiability", "score": 60, "note": "TTP attack figures and diplomatic facts verifiable"},
            {"name": "Cross-source consensus", "score": 52, "note": "Pakistani framing diverges from Afghan and Western accounts"},
            {"name": "Narrative transparency", "score": 49, "note": "Pakistani state perspective dominant, historical agency absent"},
            {"name": "Contextual completeness", "score": 45, "note": "ISI-Taliban historical relationship entirely unaddressed"},
        ],
        "source_funding": "Dawn is owned by Pakistan Herald Publications, a privately held media group. Operates under PEMRA (Pakistan Electronic Media Regulatory Authority), which has a track record of pressuring outlets on coverage of military-intelligence matters. Dawn has faced distribution blockades in the past when coverage diverged from establishment preferences.",
        "claims": [
            {"type": "fact", "text": "The Tehreek-i-Taliban Pakistan (TTP) has escalated cross-border attacks from Afghan territory since 2021"},
            {"type": "fact", "text": "Pakistan and Afghanistan held multiple rounds of diplomatic talks in Istanbul in 2024–2025"},
            {"type": "opinion", "text": "Pakistan's shift to a 'carrot-and-stick' approach represents a more mature and sustainable strategy"},
            {"type": "contested", "text": "The Afghan Taliban are unwilling and unable to restrain TTP operations against Pakistan"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "partial", "note": "Corroborates TTP escalation but includes Afghan Taliban denial of Pakistani claims"},
            {"outlet": "Al Jazeera", "stance": "partial", "note": "Reports Pakistan-Afghanistan tensions with more balance on responsibility"},
            {"outlet": "UN Monitoring Team", "stance": "diverge", "note": "Reports Taliban providing limited but real support to TTP — contradicts Pakistani framing"},
            {"outlet": "The Hindu", "stance": "diverge", "note": "Focuses on ISI's historical cultivation of Taliban as Pakistani strategic asset"},
        ],
        "narrative_beneficiary": "Pakistan's military-civilian establishment benefits from a framing that positions Pakistan as a victim of terrorism rather than a historical enabler. The 'carrot-and-stick' framing also serves to legitimise Pakistani airstrikes inside Afghanistan by portraying them as reluctant responses.",
        "missing_context": [
            "UN Monitoring Team reports consistently documenting Pakistani territory as a Taliban logistics and financial corridor",
            "ISI's documented cultivation of Haqqani Network and Quetta Shura Taliban as strategic assets from 2001–2021",
            "Pakistan's previous pattern of using 'negotiations' with TTP as tactical pauses rather than genuine disarmament processes",
        ],
    },
    {
        "article_title": "Operation Sindoor: The War on Civilians",
        "source_url": "https://www.geo.tv/latest/623772-operation-sindoor-the-war-on-civilians",
        "outlet": "Geo TV",
        "region": "india",
        "overall_score": 31,
        "verdict": "Amir Jahangir's piece in Geo TV frames Operation Sindoor entirely through Pakistani civilian casualties, without once mentioning the Pahalgam terror attack that killed 26 Indian civilians and triggered the operation. The author's WEF Country Partner Institute affiliation is foregrounded to project international legitimacy, but the piece is structurally a Pakistani government-adjacent narrative — it presents unverified casualty figures as established fact, attributes deliberate targeting of civilians without evidentiary basis, and omits all context about the terror infrastructure India stated it struck.",
        "dimensions": [
            {"name": "Source trust", "score": 38, "note": "Geo TV is Pakistan's largest private broadcaster, subject to PEMRA pressure on military affairs"},
            {"name": "Claim verifiability", "score": 32, "note": "Civilian casualty figures from Pakistani government sources only; no independent verification"},
            {"name": "Cross-source consensus", "score": 25, "note": "Framing contradicted by Indian MOD statements and neutral observers on target selection"},
            {"name": "Narrative transparency", "score": 28, "note": "WEF affiliation used to imply objectivity; Pakistani state framing not disclosed"},
            {"name": "Contextual completeness", "score": 30, "note": "Pahalgam attack context entirely absent; no mention of terror training infrastructure at strike sites"},
        ],
        "source_funding": "Geo TV is owned by Independent Media Corporation (IMC), Pakistan's largest private media group. While technically independent, Geo has faced multiple blackouts and PEMRA regulatory actions when its coverage diverged from military establishment preferences — most notably in 2014 and 2018. Editorial independence on security matters is functionally constrained. The author, Amir Jahangir, is CEO of Mishal Pakistan, a World Economic Forum Country Partner Institute — an affiliation that lends international credibility optics without providing editorial independence from Pakistani national narratives.",
        "claims": [
            {"type": "unverifiable", "text": "Operation Sindoor deliberately targeted civilian infrastructure rather than terrorist installations"},
            {"type": "opinion", "text": "The strikes constitute a war crime under international humanitarian law"},
            {"type": "contested", "text": "Pakistani government casualty figures — 31 civilians killed, 57 injured — are independently verified"},
            {"type": "unverifiable", "text": "India's strikes had no legitimate military targets and were designed to terrorise the civilian population"},
        ],
        "cross_source": [
            {"outlet": "Indian Ministry of Defence", "stance": "diverge", "note": "States all nine strike sites were Lashkar-e-Taiba and Jaish-e-Mohammed terrorist infrastructure"},
            {"outlet": "Reuters", "stance": "partial", "note": "Reports Pakistani casualty claims while noting India's stated rationale for target selection"},
            {"outlet": "Al Jazeera", "stance": "partial", "note": "Covers civilian impact but includes Indian government's operational justification"},
            {"outlet": "Dawn (Pakistan)", "stance": "agree", "note": "Pakistani outlet, echoes government framing on civilian targeting without independent verification"},
        ],
        "narrative_beneficiary": "The Pakistani military establishment and government benefit from a framing that repositions Pakistan as victim of Indian aggression rather than host to terrorist infrastructure. The WEF-affiliated author branding is strategic — it is designed to reach international audiences and build pressure for condemnation of India, bypassing the question of why the Pahalgam attack occurred.",
        "missing_context": [
            "The Pahalgam terror attack of April 22, 2025 killed 26 Indian civilians — the direct trigger for Operation Sindoor. The piece mentions Pahalgam only once, solely to dispute Pakistan's link to it, with no acknowledgment of the victims or the attack itself",
            "India named nine specific strike sites as headquarters of Lashkar-e-Taiba and Jaish-e-Mohammed; the article does not engage with whether these sites housed terror infrastructure",
            "UN-designated terrorist organisations LeT and JeM have operated openly from Pakistan for decades with documented state tolerance — context entirely absent",
        ],
    },

    # ── Low credibility ────────────────────────────────────────────────────
    {
        "article_title": "Western 'alternative' narrative detrimental to Indian infrastructure development",
        "source_url": "https://www.globaltimes.cn/page/202408/1318526.shtml",
        "outlet": "Global Times",
        "region": "india",
        "overall_score": 22,
        "verdict": "Global Times is an official organ of the Chinese Communist Party, published under People's Daily. This piece is a textbook example of CCP foreign influence strategy: using India's legitimate infrastructure ambitions to position China as India's natural partner and Western frameworks as adversarial. The 'analyst' voices are unattributed or drawn from Chinese state-adjacent think tanks. The argument is constructed to serve Beijing's geopolitical interests, not India's.",
        "dimensions": [
            {"name": "Source trust", "score": 18, "note": "CCP organ, People's Daily subsidiary, no editorial independence"},
            {"name": "Claim verifiability", "score": 22, "note": "Infrastructure claims partial; analyst attributions absent"},
            {"name": "Cross-source consensus", "score": 20, "note": "Contradicted by Indian government's own infrastructure policy"},
            {"name": "Narrative transparency", "score": 24, "note": "CCP interest in displacing Western influence not disclosed"},
            {"name": "Contextual completeness", "score": 18, "note": "China's own predatory infrastructure lending record absent"},
        ],
        "source_funding": "Global Times is published by People's Daily, the official newspaper of the Central Committee of the Communist Party of China. Fully state-funded and under direct CCP editorial control. Its English-language edition serves as a foreign-facing propaganda platform targeting international audiences.",
        "claims": [
            {"type": "opinion", "text": "Western narratives positioning India as a China alternative are designed to harm India's development"},
            {"type": "unverifiable", "text": "India's genuine interests are better served by Asian economic integration than Western frameworks"},
            {"type": "contested", "text": "Western infrastructure alternatives like G7's PGII offer less value than Asian supply chain participation"},
            {"type": "unverifiable", "text": "Western 'China+1' framing serves geopolitical containment rather than Indian economic benefit"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "diverge", "note": "India's own PLI scheme explicitly designed to attract Western firms as alternatives to China"},
            {"outlet": "Economic Times", "stance": "diverge", "note": "Documents India's deliberate policy to limit Chinese FDI and investment"},
            {"outlet": "Xinhua", "stance": "agree", "note": "Sister CCP outlet, identical framing on Western narrative containment"},
            {"outlet": "South China Morning Post", "stance": "silent", "note": "More balanced on India-China competition, does not adopt this framing"},
        ],
        "narrative_beneficiary": "The Chinese Communist Party and Chinese infrastructure firms benefit directly from undermining India's confidence in Western partnerships. The piece is part of a systematic CCP effort to prevent India from deepening economic ties with the Quad and G7 nations.",
        "missing_context": [
            "China's Belt and Road Initiative has left Sri Lanka, Pakistan, and Zambia in documented debt distress — relevant context for any India infrastructure advice from Beijing",
            "India has explicitly restricted Chinese FDI since the 2020 Galwan clashes, reflecting Indian government's own assessment of Chinese intent",
            "India's PLI (Production Linked Incentive) scheme has attracted Apple, Samsung, and dozens of Western firms — directly contradicting the article's central premise",
        ],
    },
    {
        "article_title": "WEF 2023: U.S. sanctions obsession subverts international cooperation",
        "source_url": "https://news.cgtn.com/news/2023-01-20/WEF-2023-U-S-sanctions-obsession-subverts-international-cooperation-1gKmidSxnig/index.html",
        "outlet": "CGTN",
        "region": "global",
        "overall_score": 20,
        "verdict": "CGTN is China's state international broadcasting network, operating under the CCP's Central Propaganda Department. This Davos-timed opinion piece uses the WEF's cooperation-themed agenda to delegitimise US sanctions policy — a core CCP foreign policy objective. The author selectively frames US sanctions as unilateral aggression while omitting the specific Chinese trade and security practices that triggered them. The piece is advocacy dressed as analysis.",
        "dimensions": [
            {"name": "Source trust", "score": 16, "note": "CCP-controlled foreign broadcaster, propaganda mandate"},
            {"name": "Claim verifiability", "score": 22, "note": "WEF theme cited accurately; sanctions rationale misrepresented"},
            {"name": "Cross-source consensus", "score": 18, "note": "Position contradicted by WTO rulings and allied governments"},
            {"name": "Narrative transparency", "score": 20, "note": "CCP interest in sanctions relief not acknowledged"},
            {"name": "Contextual completeness", "score": 14, "note": "Chinese IP theft and market access violations entirely absent"},
        ],
        "source_funding": "CGTN (China Global Television Network) is wholly owned and operated by CMG (China Media Group), a state entity under the CCP Central Propaganda Department. Approximately $2 billion in annual government funding. Banned from broadcasting in the UK in 2021 over content control violations. No editorial independence from Chinese state.",
        "claims": [
            {"type": "opinion", "text": "US sanctions policy contradicts the WEF's stated theme of cooperation in a fragmented world"},
            {"type": "contested", "text": "US sanctions on China target its development rather than legitimate security concerns"},
            {"type": "unverifiable", "text": "Intelligence community warnings on China are overstated to justify economic containment"},
            {"type": "unverifiable", "text": "Sanctions regimes consistently fail to achieve stated objectives and harm global stability"},
        ],
        "cross_source": [
            {"outlet": "Financial Times", "stance": "diverge", "note": "Documents specific IP theft and market access violations motivating sanctions"},
            {"outlet": "Reuters", "stance": "diverge", "note": "Reports WTO rulings against China that informed the US sanctions framework"},
            {"outlet": "Global Times", "stance": "agree", "note": "Sister CCP outlet, identical framing and narrative objectives"},
            {"outlet": "South China Morning Post", "stance": "partial", "note": "Covers tensions but includes Western government rationale for sanctions"},
        ],
        "narrative_beneficiary": "The Chinese Communist Party and Chinese state-owned enterprises are the primary beneficiaries — sanctions relief would directly benefit Chinese tech firms (Huawei, SMIC) and reduce costs of Chinese military-civil fusion programmes. The piece is timed to Davos to reach maximum elite international audience.",
        "missing_context": [
            "WTO ruled against China on subsidies and market access in over 40 disputes from 2001 to 2023 — the legal foundation for US sanctions",
            "US USTR Section 301 investigation documented $50B annually in IP theft attributable to Chinese state-sponsored actors",
            "China itself maintains extensive import restrictions, technology bans, and informal boycotts against countries that displease Beijing",
        ],
    },
    {
        "article_title": "Does Russia have a point about NATO expansion?",
        "source_url": "https://www.rt.com/russia/547775-west-europe-nato-expansion/",
        "outlet": "RT (Russia Today)",
        "region": "global",
        "overall_score": 18,
        "verdict": "RT is Russia's state foreign broadcasting arm, and while this piece is authored by a credentialled international law professor — Alfred de Zayas — its publication on RT serves a clear function: lending academic legitimacy to Russian state talking points on NATO expansion as provocation. The Kennan quote and 'assurances' argument have real scholarly debate around them, but the piece presents the most Russia-favourable version of contested history as settled fact, and was published weeks before the 2022 invasion as part of a coordinated information operation.",
        "dimensions": [
            {"name": "Source trust", "score": 14, "note": "Kremlin-funded, banned in EU and UK for disinformation"},
            {"name": "Claim verifiability", "score": 24, "note": "Kennan quote real; 'assurances' claim historically contested"},
            {"name": "Cross-source consensus", "score": 16, "note": "Isolated from mainstream historical and legal scholarship"},
            {"name": "Narrative transparency", "score": 20, "note": "Author's credentials used to mask RT's state propaganda function"},
            {"name": "Contextual completeness", "score": 14, "note": "Russian aggression timeline and Eastern European agency absent"},
        ],
        "source_funding": "RT (Russia Today) is funded by the Russian federal budget — approximately $400 million annually. It was banned from broadcasting in the EU following Russia's 2022 invasion of Ukraine and from the UK by Ofcom for editorial control violations. Operates under direct Kremlin supervision. The RT America network was shut down in 2022.",
        "claims": [
            {"type": "contested", "text": "NATO's eastward expansion violated verbal assurances given to Soviet leaders in 1990"},
            {"type": "opinion", "text": "Western provocations rather than Russian decisions caused the deterioration of European security"},
            {"type": "unverifiable", "text": "Western security experts privately acknowledge NATO expansion was a catastrophic mistake"},
            {"type": "unverifiable", "text": "Russia's concerns about NATO constitute a legitimate security interest under international law that justifies military response"},
        ],
        "cross_source": [
            {"outlet": "Der Spiegel", "stance": "diverge", "note": "Archive investigation found no binding written commitment on NATO expansion"},
            {"outlet": "Reuters", "stance": "diverge", "note": "Historical record shows no formal treaty — only informal conversations"},
            {"outlet": "Xinhua", "stance": "partial", "note": "Sympathetic to Russian framing without full endorsement"},
            {"outlet": "Le Monde Diplomatique", "stance": "partial", "note": "Acknowledges legitimate Russian security concerns but rejects invasion as justified"},
        ],
        "narrative_beneficiary": "The Russian government and Vladimir Putin's domestic political legitimacy benefit from the 'NATO provocation' narrative. The piece is designed to erode Western European public support for NATO and create false equivalence between Russian aggression and Alliance expansion. Published January 2022 — weeks before the invasion.",
        "missing_context": [
            "Every Eastern European state that joined NATO did so voluntarily after Soviet-era occupation — their agency is entirely absent from this framing",
            "Russia's 2008 invasion of Georgia and 2014 annexation of Crimea preceded Ukraine's accelerated NATO membership interest by years",
            "The 'assurances' were verbal, non-binding, and given to the Soviet Union — a state that no longer existed by the time NATO expanded",
        ],
    },

    # ── Left-leaning Indian outlets ─────────────────────────────────────────
    {
        "article_title": "India Remains an Electoral Autocracy, Slips Five Places on Liberal Democracy Index: V-Dem Report",
        "source_url": "https://m.thewire.in/article/government/democracy-declines-globally-india-among-largest-electoral-autocracies-v-dem-report",
        "outlet": "The Wire",
        "region": "india",
        "overall_score": 52,
        "verdict": "The Wire accurately reports V-Dem's 2026 findings — India at rank 105, classified as an electoral autocracy since 2017. The underlying data is real and the report is peer-reviewed. However, the piece presents V-Dem's expert-survey methodology as authoritative without engaging with its known criticisms, and frames India's democratic health exclusively through the backsliding lens — omitting that the 2024 general election saw BJP lose its outright majority, opposition gain seats, and independent courts continue to rule against the government on key cases.",
        "dimensions": [
            {"name": "Source trust", "score": 60, "note": "The Wire is credible but has acknowledged left-liberal editorial identity"},
            {"name": "Claim verifiability", "score": 65, "note": "V-Dem rankings are real and publicly verifiable — accurately cited"},
            {"name": "Cross-source consensus", "score": 50, "note": "Freedom House similarly critical; Economist Intelligence Unit more nuanced"},
            {"name": "Narrative transparency", "score": 42, "note": "Editorial position not disclosed; framing one-directional throughout"},
            {"name": "Contextual completeness", "score": 42, "note": "2024 election outcome, opposition gains, and independent judiciary absent"},
        ],
        "source_funding": "The Wire is funded through reader subscriptions, donations, and grants from foundations including Omidyar Network. It was co-founded by Siddharth Varadarajan, who has faced government sedition proceedings. The Wire has faced FCRA scrutiny and multiple legal actions from the BJP government, which creates both a real free-press concern and an acknowledged adversarial editorial position toward the ruling party.",
        "claims": [
            {"type": "fact", "text": "V-Dem's 2026 Democracy Report ranks India 105th on the liberal democracy index"},
            {"type": "fact", "text": "V-Dem has classified India as an electoral autocracy since 2017"},
            {"type": "opinion", "text": "The BJP has systematically dismantled democratic institutions since 2009"},
            {"type": "contested", "text": "India is among the world's largest electoral autocracies, comparable in kind to Hungary or Turkey"},
        ],
        "cross_source": [
            {"outlet": "Freedom House", "stance": "agree", "note": "Also rates India 'Partly Free', corroborates press freedom and civil liberty concerns"},
            {"outlet": "Economist Intelligence Unit", "stance": "partial", "note": "Classifies India as a 'Flawed Democracy' — same direction but less extreme framing"},
            {"outlet": "Indian Express", "stance": "diverge", "note": "Points to 2024 election result as evidence democratic accountability functions"},
            {"outlet": "MEA / Government of India", "stance": "diverge", "note": "Formally rejects V-Dem methodology as politically motivated and non-transparent"},
        ],
        "narrative_beneficiary": "Opposition political parties, international human rights organisations, and Western governments seeking leverage over India's foreign policy benefit from the autocracy framing. The narrative also serves The Wire's fundraising base, which is heavily composed of readers who hold an anti-BJP political position.",
        "missing_context": [
            "The 2024 general election reduced BJP from 303 to 240 seats — the opposition INDIA alliance made significant gains, indicating electoral accountability is functioning",
            "India's Supreme Court and High Courts have ruled against the government on CAA, demonetisation, and electoral bonds — independent judicial function V-Dem's framing underweights",
            "V-Dem's 'expert survey' methodology relies on the opinions of selected academics rather than objective institutional metrics — its India scores are contested by political scientists who study South Asian democracy",
        ],
    },
    {
        "article_title": "Government Orders Trigger Sweeping Instagram Censorship Days After CJP Protest",
        "source_url": "https://m.thewire.in/article/media/government-orders-trigger-sweeping-instagram-censorship-days-after-cjp-protest",
        "outlet": "The Wire",
        "region": "india",
        "overall_score": 55,
        "verdict": "The Wire reports a real and documentable phenomenon — government orders under India's IT Act have led to content restrictions on Instagram targeting accounts that covered the CJP youth protest movement. The story raises legitimate free-expression concerns. However, the piece implies direct political causation (protest → censorship) without establishing that the orders specifically targeted protest coverage rather than other content categories, and does not engage with the legal basis under Section 69A of the IT Act under which such orders operate.",
        "dimensions": [
            {"name": "Source trust", "score": 60, "note": "The Wire has credible digital rights reporting track record"},
            {"name": "Claim verifiability", "score": 62, "note": "Government content removal orders are real and partially verifiable via Lumen Database"},
            {"name": "Cross-source consensus", "score": 58, "note": "Internet Freedom Foundation and multiple journalists corroborate platform restrictions"},
            {"name": "Narrative transparency", "score": 50, "note": "Causal link (protest triggered orders) implied but not established with documentary evidence"},
            {"name": "Contextual completeness", "score": 45, "note": "IT Act Section 69A legal framework and scope of orders not explained"},
        ],
        "source_funding": "The Wire is reader-supported via subscriptions and foundation grants. It is in an active adversarial legal relationship with the current government, having faced sedition charges, FCRA notices, and multiple defamation suits. This gives The Wire both genuine incentive to document state censorship and structural motivation to frame government actions in the most alarming possible terms.",
        "claims": [
            {"type": "fact", "text": "Instagram accounts covering the CJP protest faced content restrictions and takedowns following government orders"},
            {"type": "contested", "text": "The censorship was specifically triggered by the CJP's Sansad Chalo protest on July 20, 2026"},
            {"type": "opinion", "text": "The government's content orders represent a deliberate strategy to suppress political dissent online"},
            {"type": "unverifiable", "text": "The orders were issued without transparency regarding which content or accounts were targeted and on what grounds"},
        ],
        "cross_source": [
            {"outlet": "Internet Freedom Foundation", "stance": "agree", "note": "IFF has documented IT Act content orders and platform compliance patterns independently"},
            {"outlet": "Times of India", "stance": "silent", "note": "Did not report on Instagram censorship angle; covered CJP protests without digital rights framing"},
            {"outlet": "NDTV", "stance": "partial", "note": "Reported platform restrictions but did not link directly to CJP protest response"},
            {"outlet": "Ministry of Electronics & IT", "stance": "diverge", "note": "Government maintains content orders comply with IT Act and target illegal content, not political speech"},
        ],
        "narrative_beneficiary": "The CJP protest movement and its media allies benefit from a censorship framing that elevates the protests' legitimacy and delegitimises the government response. International press freedom organisations (RSF, CPJ) benefit from documentation for annual rankings. The Wire's readership and donor base respond strongly to digital rights and censorship stories.",
        "missing_context": [
            "Section 69A of India's IT Act legally permits the government to issue content blocking orders without public disclosure — the legal framework exists independent of political motivation",
            "India has a documented pattern of IT Act content orders across multiple governments, including Congress-era administrations — this is not exclusively a BJP-era phenomenon",
            "The specific accounts and content targeted in the orders were not identified in the article, making the direct causal link between the protest and the censorship unverifiable",
        ],
    },
    {
        "article_title": "'Nothing Less Will Work': After Meeting With Nadda, Jitender, CJP Gives 48-Hour Deadline",
        "source_url": "https://m.thewire.in/article/rights/cjp-gives-48-hour-ultimatum-warns-centre-of-bigger-nationwide-protest",
        "outlet": "The Wire",
        "region": "india",
        "overall_score": 58,
        "verdict": "This is closer to straight news than analysis — The Wire accurately reports the CJP youth movement's demands and the July 24 meeting with BJP leaders JP Nadda and Jitendra Singh. The facts are largely verifiable and the protest events are real. However, the framing consistently positions the CJP as the righteous party and the government as stonewalling, without meaningfully engaging with the government's stated position on NEET reform or the fast-track court proposal that CJP dismissed. The headline framing ('Nothing Less Will Work') quotes the protest group without a government counter-quote.",
        "dimensions": [
            {"name": "Source trust", "score": 62, "note": "The Wire's protest reporting is credible; byline is Wire Staff, not a named correspondent"},
            {"name": "Claim verifiability", "score": 70, "note": "Meeting facts, protest timeline, and demands are verifiable from multiple sources"},
            {"name": "Cross-source consensus", "score": 62, "note": "CJP protest events confirmed across Indian media; government framing diverges"},
            {"name": "Narrative transparency", "score": 52, "note": "Protest sympathetic framing not disclosed; government position underrepresented"},
            {"name": "Contextual completeness", "score": 46, "note": "Government's NEET reform proposal and CJI-monitored fast-track courts not meaningfully covered"},
        ],
        "source_funding": "The Wire is reader-funded via subscriptions and foundations. Its editorial identity is explicitly left-liberal and it has positioned itself as a watchdog against the current BJP government. This does not disqualify its reporting but shapes which protest movements receive sympathetic coverage and which government responses receive scrutiny.",
        "claims": [
            {"type": "fact", "text": "CJP representatives met BJP leaders JP Nadda and Jitendra Singh on July 24, 2026"},
            {"type": "fact", "text": "CJP demanded the resignation of Education Minister Dharmendra Pradhan over NEET paper leaks"},
            {"type": "opinion", "text": "The government's fast-track court proposal was an inadequate and deflecting response to the protesters' demands"},
            {"type": "contested", "text": "The CJP protest represented a significant democratic challenge that forced the government onto the backfoot"},
        ],
        "cross_source": [
            {"outlet": "NDTV", "stance": "partial", "note": "Confirmed protest events and government meeting; more balanced on government's stated reform intentions"},
            {"outlet": "Indian Express", "stance": "partial", "note": "Reported demands and meeting; included government spokesperson's position more fully"},
            {"outlet": "Times of India", "stance": "silent", "note": "Covered NEET controversy but gave less prominence to CJP ultimatum framing"},
            {"outlet": "Government press release", "stance": "diverge", "note": "Government characterised meeting as productive dialogue; said fast-track courts addressed core concern"},
        ],
        "narrative_beneficiary": "The CJP youth movement and opposition parties benefit from The Wire's framing, which positions their demands as non-negotiable democratic imperatives and the government's response as evasion. Left-of-centre political parties seeking to capitalise on student disillusionment benefit from this coverage amplifying the protest as a broader governance failure.",
        "missing_context": [
            "The government did subsequently withdraw the FCRA Amendment Bill and the delimitation bill — concessions The Wire later reported but which were not visible at the time of this piece",
            "The NEET paper leak originated from a network of coaching centres and individual conspirators — systemic government negligence was one interpretation; criminal conspiracy by private actors was another, equally supported by the FIR evidence",
            "Fast-track CJI-monitored courts were a real institutional concession, not a deflection — The Wire's framing that 'nothing less will work' dismisses a substantive offer without engaging its merits",
        ],
    },
    {
        "article_title": "CJP Protests: Why Public Demonstrations Need Police Permission In India",
        "source_url": "https://www.outlookindia.com/national/cjp-protests-why-public-demonstrations-need-police-permission-in-india",
        "outlet": "Outlook India",
        "region": "india",
        "overall_score": 50,
        "verdict": "Pranay Vatsa's Outlook piece uses the CJP protest as a peg to explain India's legal framework for public demonstrations under Article 19. The constitutional analysis is broadly accurate. However, the article's implicit framing — that police permission requirements are themselves a restriction on democratic protest — understates the legitimate public order rationale for permit systems, and does not engage with the fact that India's higher courts have repeatedly upheld the constitutional validity of these frameworks. The legal explainer doubles as editorial commentary without clearly separating the two.",
        "dimensions": [
            {"name": "Source trust", "score": 52, "note": "Outlook India is a credible legacy publication but has a tabloid-adjacent sensationalism tendency"},
            {"name": "Claim verifiability", "score": 60, "note": "Article 19 provisions and court precedents cited are factually verifiable"},
            {"name": "Cross-source consensus", "score": 50, "note": "Legal framework accurately described; editorial framing of restrictions as problematic is contested"},
            {"name": "Narrative transparency", "score": 46, "note": "Editorial sympathy toward protest movement embedded in what is framed as neutral legal analysis"},
            {"name": "Contextual completeness", "score": 42, "note": "Court precedents upholding permit systems and comparative international standards absent"},
        ],
        "source_funding": "Outlook India is published by the Outlook Group, owned by Mahinda Srinivas Reddy. It is privately held and primarily advertising-funded. The outlet has historically positioned itself as a liberal counterweight to pro-government print media and has editorial sympathies that lean left-of-centre on civil liberties issues.",
        "claims": [
            {"type": "fact", "text": "Article 19(1)(b) of the Indian Constitution guarantees the right to peaceful assembly"},
            {"type": "fact", "text": "Public demonstrations in India generally require police permission for venues like public roads and parks"},
            {"type": "opinion", "text": "The requirement for police permission creates a structural impediment to the exercise of democratic protest rights"},
            {"type": "contested", "text": "The CJP protest restrictions reflected selective enforcement based on political content rather than neutral public order concerns"},
        ],
        "cross_source": [
            {"outlet": "LiveLaw", "stance": "partial", "note": "Legal reporting confirms Article 19 framework; notes courts uphold permit requirements as reasonable restrictions"},
            {"outlet": "Bar and Bench", "stance": "partial", "note": "Documents protest FIR cases but provides fuller legal context than Outlook piece"},
            {"outlet": "Indian Express", "stance": "diverge", "note": "Editorial noted CJP achieved its goals despite permit hurdles — undermining the 'structural impediment' framing"},
            {"outlet": "Ministry of Home Affairs", "stance": "diverge", "note": "States permission requirements apply uniformly to all organisations regardless of political affiliation"},
        ],
        "narrative_beneficiary": "The CJP protest movement and civil liberties organisations benefit from a framing that positions the permit system as an anti-democratic tool. Left-liberal readers and international human rights audiences, who are Outlook's online readership base, are the primary audience for this framing.",
        "missing_context": [
            "The Supreme Court has repeatedly upheld the validity of police permission for public assemblies as a 'reasonable restriction' under Article 19(2) — the permit system is constitutionally settled law, not a contested imposition",
            "Comparable democracies including the UK, France, and Germany require advance notification or permits for public demonstrations — India's framework is not globally exceptional",
            "The CJP protest ultimately succeeded in forcing government concessions, suggesting the permit system did not prevent effective democratic protest — the article's framing of structural impediment is contradicted by the outcome",
        ],
    },

    # ── Right-of-centre Indian outlet ────────────────────────────────────────
    {
        "article_title": "Inside India's Air Defence Network That Stood Tall During Operation Sindoor",
        "source_url": "https://swarajyamag.com/defence/inside-indias-air-defence-network-that-stood-tall-during-operation-sindoor",
        "outlet": "Swarajya",
        "region": "india",
        "overall_score": 53,
        "verdict": "Prakhar Gupta's Swarajya piece is technically detailed and largely accurate on India's air defence systems — S-400, MRSAM, Akash, and the integrated command network. The military hardware described is real and verifiable. The editorial problem is one-directionality: the piece frames Operation Sindoor's air defence performance as an unqualified success, without engaging Pakistani claims of drone interceptions or independent assessments of system effectiveness. The headline framing ('Stood Tall') is advocacy; the technical content underneath is genuinely informative.",
        "dimensions": [
            {"name": "Source trust", "score": 58, "note": "Swarajya is independent but explicitly right-of-centre with pro-establishment defence editorial stance"},
            {"name": "Claim verifiability", "score": 62, "note": "Air defence system specifications are publicly documented and verifiable"},
            {"name": "Cross-source consensus", "score": 50, "note": "Technical facts broadly corroborated; operational success claims not independently verified"},
            {"name": "Narrative transparency", "score": 55, "note": "Swarajya's editorial lean is known; framing celebratory but not concealed"},
            {"name": "Contextual completeness", "score": 42, "note": "Pakistani drone penetration claims and independent battle damage assessments absent"},
        ],
        "source_funding": "Swarajya is an independent Indian media outlet with an explicitly right-of-centre, nationalist editorial identity. It is funded through subscriptions and reader support, with no direct government or corporate conglomerate funding. Founded in 1956, revived in 2014, it positions itself as a counterweight to left-liberal Indian media. Authors publish under their own bylines with editorial oversight.",
        "claims": [
            {"type": "fact", "text": "India deployed the S-400 Triumf (Sudarshan Chakra), MRSAM, and Akash systems during Operation Sindoor"},
            {"type": "fact", "text": "Pakistan fired drones and missiles at Indian military installations during the operation"},
            {"type": "contested", "text": "India's integrated air defence network neutralised all Pakistani aerial threats without any successful penetration"},
            {"type": "opinion", "text": "Operation Sindoor demonstrated India's emergence as a mature military power with credible multi-layered air defence"},
        ],
        "cross_source": [
            {"outlet": "The Hindu", "stance": "partial", "note": "Confirms air defence deployment; more cautious on 'zero penetration' claims"},
            {"outlet": "Reuters", "stance": "partial", "note": "Reports air defence activation; notes independent verification of outcomes is not possible"},
            {"outlet": "ISPR (Pakistan)", "stance": "diverge", "note": "Claims Pakistani drones successfully struck Indian military sites in Jammu and Pathankot"},
            {"outlet": "War on the Rocks", "stance": "partial", "note": "Notes India's air defence credibility was tested and generally held; cautious on total success claims"},
        ],
        "narrative_beneficiary": "The Indian defence establishment and BJP government benefit from a narrative of technological self-reliance and military competence. Swarajya's readership — nationalist, defence-interested, pro-India — receives the operation as validation of the Modi government's defence modernisation programme. The framing supports the political case for continued defence capital expenditure.",
        "missing_context": [
            "Pakistan's ISPR claimed drone strikes successfully reached Indian military airbases at Jammu and Pathankot — Swarajya does not engage with these counter-claims",
            "Independent battle damage assessment of Indian air defence performance has not been published by any neutral third-party military analyst",
            "The S-400's actual engagement record during Sindoor remains classified — the piece presents system specifications as proof of operational success, which is a logical gap",
        ],
    },

    # ── Government source ────────────────────────────────────────────────────
    {
        "article_title": "Operation SINDOOR — Official Government Position",
        "source_url": "https://www.mea.gov.in/operation-sindoor",
        "outlet": "Ministry of External Affairs, India",
        "region": "official",
        "overall_score": 36,
        "verdict": "The MEA's Operation Sindoor page is official government communication — transparent in its source but inherently one-sided by function. The factual claims about the Pahalgam attack and the names of terror organisations struck are largely verifiable against independent sources. However, the framing exclusively presents the Indian government's narrative: civilian harm is dismissed, casualty figures are presented from the Indian military's perspective only, and the diplomatic and humanitarian dimensions are absent. This is government communication functioning exactly as intended — advocacy, not journalism.",
        "dimensions": [
            {"name": "Source trust", "score": 25, "note": "Official government source — transparent but zero editorial independence"},
            {"name": "Claim verifiability", "score": 60, "note": "Strike sites, terror group names, and Pahalgam attack date are independently verifiable"},
            {"name": "Cross-source consensus", "score": 35, "note": "Indian military facts corroborated; '100+ terrorists killed' figure disputed by independent analysts"},
            {"name": "Narrative transparency", "score": 22, "note": "No acknowledgment that this is advocacy; framed as factual record"},
            {"name": "Contextual completeness", "score": 38, "note": "Civilian casualties, ceasefire terms, and US/China mediation entirely absent"},
        ],
        "source_funding": "The Ministry of External Affairs is funded entirely by the Government of India. This page is official state communication — the government of India's formal record of its own military operation. No editorial independence exists by design. The purpose of the page is to present India's legal, strategic, and moral justification for Operation Sindoor to domestic and international audiences.",
        "claims": [
            {"type": "fact", "text": "Operation Sindoor was launched May 7, 2025 in response to the Pahalgam terror attack of April 22, 2025 which killed 26 civilians"},
            {"type": "fact", "text": "India struck nine sites associated with Jaish-e-Mohammed, Lashkar-e-Taiba, and Hizbul Mujahideen in Pakistan and PoK"},
            {"type": "contested", "text": "Over 100 terrorists were killed, with all strikes avoiding civilian infrastructure"},
            {"type": "unverifiable", "text": "The operation was conducted with 'operational ethics' and no civilian casualties were caused by Indian strikes"},
        ],
        "cross_source": [
            {"outlet": "Reuters", "stance": "partial", "note": "Confirms operation facts and terror group affiliations; includes Pakistani civilian casualty claims India disputes"},
            {"outlet": "Geo TV (Pakistan)", "stance": "diverge", "note": "Frames strikes as targeting civilian infrastructure with 31 civilian deaths"},
            {"outlet": "War on the Rocks", "stance": "partial", "note": "Corroborates strategic rationale; more cautious on casualty and targeting precision claims"},
            {"outlet": "Al Jazeera", "stance": "partial", "note": "Reports both Indian government claims and Pakistani counter-narrative without adjudicating"},
        ],
        "narrative_beneficiary": "The Indian government and BJP leadership benefit from a framing that presents Operation Sindoor as a clean, precise, and ethically executed counter-terror operation. The page serves to build domestic consensus, preempt international criticism, and establish India's legal justification under Article 51 of the UN Charter for the international record.",
        "missing_context": [
            "Pakistani government and independent journalists reported 31 civilian deaths across the strike sites — the MEA page does not engage with these claims or provide a counter-analysis",
            "A ceasefire was brokered within days, reportedly with US and Chinese diplomatic involvement — the diplomatic resolution is entirely absent from the government's framing",
            "The '100+ terrorists killed' figure has not been independently verified by any neutral party — the claim is repeated as established fact without sourcing",
        ],
    },
]
